version: '3.8'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    image: felipenoguez/app-node:v1
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    tty: true
    ports:
      - 3000:3000


  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbmysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge