version: '3.8'

services:
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "-proot"]
      interval: 20s
      timeout: 15s
      retries: 30

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    image: felipenoguez/app-node:v1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:1.17.10
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - node-network
    depends_on:
      - app
      - db
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
  
networks:
  node-network:
    driver: bridge