version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    image: felipenoguez/laravel:prod
    container_name: laravel-container
    networks:
      - laranet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: felipenoguez/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80
  
networks:
  laranet:
    driver: bridge