version: '3.8'

services:
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbmysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge