apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: felipenoguez/hello-go:v6
        imagePullPolicy: Always
        
        # aqui é onde definimos os recursos do container        
        resources:
          requests:
            memory: "20Mi"
            cpu: "0.05"
          limits:
            memory: "25Mi"
            cpu: "0.1"

        # com o uso do startup probe, o initialDelaySeconds probe não é mais necessário
        # pois o startup probe irá garantir que o container esteja pronto antes de iniciar as outras probes
        startupProbe:
          httpGet:
            path: /healthz
            port: 1078
          periodSeconds: 3
          failureThreshold: 30
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1078
          periodSeconds: 3
          failureThreshold: 1
          # initialDelaySeconds: 10

        # descomentado liveness probe para testar o readiness probe
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1078
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
          # initialDelaySeconds: 15

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        
        volumeMounts:
          - name: config-volume
            mountPath: /go/myfamily
            # The file will be created in the container at the specified path
            readOnly: true
          - name: goserver-volume # aqui devemos chamar o nome do volume definido no volumes
            mountPath: /go/data # caminho onde o volume será montado no container
            # O volume será montado no caminho especificado dentro do container
            readOnly: false # o volume será montado como leitura e escrita

      volumes:
        - name: goserver-volume # pode ser qualquer nome para o volume
          persistentVolumeClaim:
            claimName: goserver-pvc # nome do PVC criado no arquivo pvc.yaml
        - name: config-volume
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
