FROM node:latest

WORKDIR /usr/src/app

# RUN apt-get update && apt-get install -y npm

# RUN npm init -y 
# RUN npm install express

# RUN npm init -y \
#     && npm install express
    
# COPY . .

EXPOSE 3000

# ENTRYPOINT [ "npm init -y", "npm install express" ]

CMD [ "node", "index.js" ]