FROM node:latest

# Aqui para o ambiente de desenvolvimento, se instalar e atualiza o que for necessário:
# RUN apt-get install <nome_da_dependencia>

WORKDIR /usr/src/app

# COPY . . remover para ambiente DEV

EXPOSE 3000

CMD [ "node", "index.js" ]