apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: felipenoguez/hello-go:v8
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1078
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10

        # comentado liveness probe para testar o readiness probe
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8000
        #   periodSeconds: 5
        #   failureThreshold: 3
        #   timeoutSeconds: 1
        #   successThreshold: 1

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        
        volumeMounts:
          - name: config-volume
            mountPath: /go/myfamily
            # The file will be created in the container at the specified path
            readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
