name: ci-sonarcloud
on: 
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Run tests
      run: go test ./integracao-continua/7-sonarqube/7.6-preparando-ambiente-para-sonarcloud/goapp/-coverprofile=coverage.out