name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:  
  check:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: [ '1.13', '1.15' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        # go-version: ${{ matrix.go }}
    # - name: Run tests
    #   run: go test ./integracao-continua/2-iniciando-com-ci/goapp/
    - name: Run app
      run: go run ./integracao-continua/2-iniciando-com-ci/goapp/math.go
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./integracao-continua/2-iniciando-com-ci/goapp/
        push: false
        tags: felipenoguez/fullcycle:latest
