name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13', '1.15' ]
    name: Go ${{ matrix.go }} sample
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: go run ./integracao-continua/2-iniciando-com-ci/goapp/math.go